language: java
sudo: false

notifications:
  email: alper.cinaroglu@gmail.com

dist: focal

jdk:
  - openjdk11

git:
  depth: false

# Sonar cloud addons on travis has some issues so that it's used directly 
#addons:
#  sonarcloud:
#    organization: "ant-media"
#    token: $SONAR_TOKEN

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V --quiet

script:
  - export RELEASE_VERSION="$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)"
  - echo $RELEASE_VERSION
  # option to add above (-Dtest="MuxerUnitTest")  for running custom tests
  - mvn org.owasp:dependency-check-maven:check --quiet
  #depedency vulnerability check

  - ./run.sh -f output.mp4 -m publisher -n 1 -s 10.10.175.53  #publishes output.mp4 to the server with default name myStream
  - ./run.sh -m player -n 100 -i stream1 -s 10.10.175.53 -u false #plays 100 viewers for default stream myStream